### ISSUE TITLE
Which paper does the implementation detail relate to?

### ISSUE THREAD

**Issue by Gorluxor** [rosinality/denoising-diffusion-pytorch#7]
Hey rosinality, 

I have a question regarding the implementation. 

Does this implementation relate to [https://arxiv.org/abs/2006.11239](https://arxiv.org/abs/2006.11239) and subsequently [https://github.com/hojonathanho/diffusion](https://github.com/hojonathanho/diffusion) github? 
As in are we suppose to expect similar results. 

Also regarding your training, did you use the default 8 batch size? or something else? 
As in the Paper they used TPU v3-8 (similar to 8 V100 GPUs) with batch size 64. 

Great work on the repo!

**Comment by rosinality** [comment]
Yes, this repository related on that paper/implementation. I have used 8 batch size * 8 gpus = 64 total batch size.
